name: Integration Testsuite

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - '.github/workflows/integration.yml'
    - '**'
    - '!adapters/**'
    - 'adapters/substrate/**'
    - '!fixtures/**'
    - 'fixtures/genesis/**'
    - '!helpers/AdapterFixture.jl'
    - '!runtimes/hostapi/**'
    - '!README.md'

jobs:
  build-host-substrate:
    name: "[build] substrate-host"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup rust toolchain
      id: rustup
      uses: actions-rs/toolchain@v1
      with:
        target: wasm32-unknown-unknown
        default: true
        profile: minimal
    - name: Cache cargo registry and index
      uses: actions/cache@v2.1.6
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-cache-host-substrate-${{ hashFiles('hosts/substrate/Cargo.lock') }}
        restore-keys: cargo-cache-host-substrate-
    - name: Cache cargo build output
      uses: actions/cache@v2.1.6
      with:
        path: hosts/substrate/target
        key: cargo-build-host-substrate-${{ steps.rustup.outputs.rustc_hash }}-${{ hashFiles('hosts/substrate/Cargo.lock') }}
        restore-keys: cargo-build-host-substrate-${{ steps.rustup.outputs.rustc_hash }}-
    - name: Build substrate
      run: make substrate-host
    - name: Upload substrate
      uses: actions/upload-artifact@v2
      with:
        name: substrate-host
        path: bin/polkadot

  build-host-kagome:
    name: "[build] kagome-host"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Cache hunter outputs
      uses: actions/cache@v2.1.6
      with:
        path: ~/.hunter
        key: hunter-host-kagome-${{ hashFiles('hosts/kagome/CMakeLists.txt') }}
        restore-keys: hunter-host-kagome-
    - name: Build kagome
      env:
        CC: gcc-9
        CXX: g++-9
      run: make kagome-host
    - name: Upload kagome hosts
      uses: actions/upload-artifact@v2
      with:
        name: kagome-host
        path: |
          bin/kagome

  build-host-gossamer:
    name: "[build] gossamer-host"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Cache go modules
      uses: actions/cache@v2.1.6
      with:
        path: ~/go/pkg/mod
        key: go-mod-host-gossamer-${{ hashFiles('hosts/gossamer/go.sum') }}
        restore-keys: go-mod-host-gossamer-
    - name: Build gossamer
      run: make gossamer-host
    - name: Upload gossamer and libwasmer
      uses: actions/upload-artifact@v2
      with:
        name: gossamer-host
        path: bin/gossamer
    - name: Upload libwasmer.so
      uses: actions/upload-artifact@v2
      with:
        name: gossamer-host
        path: lib/libwasmer.so


  build-adapter-substrate:
    name: "[build] substrate-adapter"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup rust toolchain
      id: rustup
      uses: actions-rs/toolchain@v1
      with:
        target: wasm32-unknown-unknown
        default: true
        profile: minimal
    - name: Cache cargo registry and index
      uses: actions/cache@v2.1.6
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-cache-adapter-substrate-${{ hashFiles('adapters/substrate/Cargo.lock') }}
        restore-keys: cargo-cache-adapter-substrate-
    - name: Cache cargo build ouput
      uses: actions/cache@v2.1.6
      with:
        path: adapters/substrate/target
        key: cargo-build-adapter-substrate-${{ steps.rustup.outputs.rustc_hash }}-${{ hashFiles('adapters/substrate/Cargo.lock') }}
        restore-keys: cargo-build-adapter-substrate-${{ steps.rustup.outputs.rustc_hash }}-
    - name: Build substrate adapters
      run: make substrate-adapter
    - name: Upload substrate adapter
      uses: actions/upload-artifact@v2
      with:
        name: substrate-adapter
        path: bin/substrate-adapter


  build-runtime-tester:
    name: "[build] tester-runtime"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup rust toolchain
      id: rustup
      uses: actions-rs/toolchain@v1
      with:
        target: wasm32-unknown-unknown
        default: true
        profile: minimal
    - name: Setup python toolchain
      uses: actions/setup-python@v2
    - name: Install yq
      run: |
        python -m pip install wheel
        python -m pip install yq
    - name: Cache cargo registry and index
      uses: actions/cache@v2.1.6
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-cache-runtime-tester-${{ hashFiles('runtimes/tester/Cargo.lock') }}
        restore-keys: cargo-cache-runtime-tester-
    - name: Cache cargo build output
      uses: actions/cache@v2.1.6
      with:
        path: runtimes/tester/target
        key: cargo-build-runtime-tester-${{ steps.rustup.outputs.rustc_hash }}-${{ hashFiles('runtimes/tester/Cargo.lock') }}
        restore-keys: cargo-build-runtime-tester-${{ steps.rustup.outputs.rustc_hash }}-
    - name: Build and generate host tester genesis
      run: make tester-runtime
    - name: Upload host tester runtime
      uses: actions/upload-artifact@v2
      with:
        name: tester_runtime.compact.wasm
        path: runtimes/tester/target/release/wbuild/tester-runtime/tester_runtime.compact.wasm
    - name: Upload host tester genesis and state file
      uses: actions/upload-artifact@v2
      with:
        name: tester-runtime-genesis
        path: |
          runtimes/tester/genesis.json
          runtimes/tester/genesis.yaml


  test-substrate:
    needs: [ build-host-substrate, build-adapter-substrate, build-runtime-tester ]
    name: "[test-genesis] substrate"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: substrate-host
        path: bin
    - run: chmod +x bin/polkadot
    - uses: actions/download-artifact@v2
      with:
        name: substrate-adapter
        path: bin
    - run: chmod +x bin/substrate-adapter
    - uses: actions/download-artifact@v2
      with:
        name: tester-runtime-genesis
        path: runtimes/tester
    - name: Run substrate with tester genesis
      run: ./runtests.jl substrate genesis

  test-kagome:
    needs: [ build-host-kagome, build-adapter-substrate, build-runtime-tester ]
    name: "[test-genesis] kagome"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: kagome-host
        path: bin
    - run: chmod +x bin/kagome
    - uses: actions/download-artifact@v2
      with:
        name: substrate-adapter
        path: bin
    - run: chmod +x bin/substrate-adapter
    - uses: actions/download-artifact@v2
      with:
        name: tester-runtime-genesis
        path: runtimes/tester
    - name: Run kagome with tester genesis
      run: ./runtests.jl kagome genesis

  test-gossamer:
    needs: [ build-host-gossamer, build-adapter-substrate, build-runtime-tester ]
    name: "[test-genesis] gossamer"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: gossamer-host
        path: bin
    - run: |
        chmod +x bin/gossamer
        mkdir -p lib
        mv bin/libwasmer.so lib/
    - uses: actions/download-artifact@v2
      with:
        name: substrate-adapter
        path: bin
    - run: chmod +x bin/substrate-adapter
    - uses: actions/download-artifact@v2
      with:
        name: tester-runtime-genesis
        path: runtimes/tester
    - name: Run gossamer with tester genesis
      run: ./runtests.jl gossamer genesis
